### ISSUE TITLE
different file format?

### ISSUE THREAD

**Issue by xc611** [thibo73800/deep_generation#1]
Hi, 

I try to run your code but got an error:

python train.py

then

python use.py checkpoints/dump_model_10.ckpt.data-00000-of-00001

received this error:

DataLossError (see above for traceback): Unable to open table file checkpoints/dump_model_10.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

Jack

**Comment by thibo73800** [comment]
I think the path is wrong.

Try this instead : 
`python use.py checkpoints/dump_model_10.ckpt
`

Keep me notified
